import { defineArrayMember, defineField, defineType } from 'sanity';
export const homepage = defineType({
  name: 'homepage',
  title: 'Homepage',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Welcome', default: true },
    { name: 'about', title: 'Our story' },
    { name: 'featured', title: 'Featured content' },
    { name: 'philosophy', title: 'Philosophy' },
    { name: 'contact', title: 'Contact invitation' },
  ],
  fields: [
    defineField({
      name: 'heroTitle',
      title: 'Main heading',
      type: 'text',
      rows: 2,
      group: 'hero',
      description: 'Usually your cattery name. A line break creates a new line in the heading.',
    }),
    defineField({ name: 'heroSubtitle', title: 'Subtitle', type: 'string', group: 'hero' }),
    defineField({
      name: 'heroDescription',
      title: 'Short introduction',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroImage',
      title: 'Main photograph',
      type: 'contentImage',
      group: 'hero',
    }),
    defineField({
      name: 'secondaryHeroImage',
      title: 'Small overlapping photograph (optional)',
      type: 'contentImage',
      group: 'hero',
    }),
    defineField({
      name: 'heroImageCaption',
      title: 'Photo caption',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'primaryCTA',
      title: 'Main button',
      type: 'cta',
      group: 'hero',
      initialValue: { label: 'Meet our cats', href: '/our-cattery' },
    }),
    defineField({
      name: 'secondaryCTA',
      title: 'Second button',
      type: 'cta',
      group: 'hero',
      initialValue: { label: 'Our litters', href: '/litters' },
    }),
    defineField({ name: 'aboutHeading', title: 'Story heading', type: 'string', group: 'about' }),
    defineField({ name: 'aboutContent', title: 'Your story', type: 'richText', group: 'about' }),
    defineField({
      name: 'aboutImage',
      title: 'Story photograph',
      type: 'contentImage',
      group: 'about',
    }),
    defineField({
      name: 'featuredCatsHeading',
      title: 'Cats heading',
      type: 'string',
      group: 'featured',
    }),
    defineField({
      name: 'featuredCats',
      title: 'Featured cats',
      type: 'array',
      group: 'featured',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{ type: 'cat' }],
          options: { filter: 'active != false' },
        }),
      ],
      validation: (rule) => rule.unique().max(6),
      description: 'Drag to reorder. Leave empty to use cats marked “Feature on the homepage”.',
    }),
    defineField({
      name: 'featuredLittersHeading',
      title: 'Litters heading',
      type: 'string',
      group: 'featured',
    }),
    defineField({
      name: 'featuredLitters',
      title: 'Featured litters',
      type: 'array',
      group: 'featured',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{ type: 'litter' }],
          options: { filter: 'active != false' },
        }),
      ],
      validation: (rule) => rule.unique().max(4),
    }),
    defineField({
      name: 'philosophyHeading',
      title: 'Philosophy heading',
      type: 'string',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyContent',
      title: 'Philosophy',
      type: 'richText',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyImage',
      title: 'Philosophy photograph',
      type: 'contentImage',
      group: 'philosophy',
    }),
    defineField({
      name: 'galleryHeading',
      title: 'Gallery heading',
      type: 'string',
      group: 'featured',
    }),
    defineField({
      name: 'galleryPreview',
      title: 'Gallery preview',
      type: 'array',
      group: 'featured',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'galleryImage' }] })],
      validation: (rule) => rule.unique().max(8),
      description: 'Choose a few photographs, then drag them into your preferred order.',
    }),
    defineField({
      name: 'exhibitionHeading',
      title: 'Exhibition heading',
      type: 'string',
      group: 'featured',
    }),
    defineField({
      name: 'featuredExhibition',
      title: 'Featured exhibition',
      type: 'reference',
      to: [{ type: 'exhibition' }],
      group: 'featured',
    }),
    defineField({
      name: 'contactCTAHeading',
      title: 'Contact heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactCTADescription',
      title: 'Contact text',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
  ],
  preview: { prepare: () => ({ title: 'Homepage', subtitle: 'The welcome to your cattery' }) },
});
